### PR TITLE
Starting to work on wildcard path matching.

### PR DESCRIPTION
**Pull request by mdobson**
WIP

### CODE REVIEW

**Comment by jaskarangump** [comment]
@mdobson - 
I tried a proxy for the backend service at /abc/*/xyz. So the proxy was created as follows
- proxy BasePath - /abc/*/xyz
- target Url - <target_host>/abc/*/xyz

When the request is made to <proxy_host>/abc/1/xyz
1. The correct proxy is executed (/)
2. The request to target is /abc/*/xyz instead of /abc/1/xyz. (x)
i.e the variable is not replacing.

Can you please let me know if this is expected.

**Comment by jaskarangump** [comment]
One more issue with proxy configuration as follows - 
proxy BasePath - /abc/*
target Url - <target_host>/abc/*

When the request is made to <proxy_host>/abc/1
- The request to target is /abc/*1
i.e both asterisk and 1 are coming in the request

**Comment by srinandan** [comment]
@jaskarangump, this feature add support for wildcards only for basePaths, not target endpoints.

**Comment by jaskarangump** [comment]
Thanks @srinandan for your suggestion about using a plugin.
We did found another peculiar issue. We tested with 3 proxies as follows - 
1. edgemicro_abc - /abc
2. edgemicro_abc__ - /abc/*
3. edgemicro_abc_xyz - /abc/*/xyz

The correct proxy was picked up for different paths, but when query parameters were passed, we got a 403 status back from microgateway.
Below are the test execution results. Two of the cases failed where query parameters were passed.

Request path: /abc
Proxy: edgemicro_abc
Target: /abc
Test Status: PASS

Request path: /abc?x=y
Proxy: edgemicro_abc
Target: N/A. Proxy returned 403
Test Status: FAIL

Request path: /abc/123
Proxy: edgemicro_abc__
Target: /abc/123
Test Status: PASS

Request path: /abc/123?x=y
Proxy: edgemicro_abc__
Target: /abc/123?x=y
Test Status: PASS

Request path: /abc/123/xyz
Proxy: edgemicro_abc__xyz
Target: /abc/123/xyz
Test Status: PASS

Request path: /abc/123/xyz?x=y
Proxy: edgemicro_abc__xyz
Target: N/A. Proxy returned 403
Test Status: FAIL

Request path: /abc/123/11
Proxy: edgemicro_abc__
Target: /abc/123/11
Test Status: PASS

Request path: /abc/123/11?x=y
Proxy: edgemicro_abc__
Target: /abc/123/11?x=y
Test Status: PASS

Request path: /abc/123/xyz/11
Proxy: edgemicro_abc__xyz
Target: /abc/123/xyz/11
Test Status: PASS

Request path: /abc/123/xyz/11?x=y
Proxy: edgemicro_abc__xyz
Target: /abc/123/xyz/11?x=y
Test Status: PASS

**Pull request merged**
